const User = require('../models/user.model')
const Availability = require('../models/availability.model')
const Schedule = require('../models/schedule.model')

exports.setAvailability = async (req, res) => {
    try {

    } catch(error) {
        console.error(error);
        return res.status(500).json({ e: "Internal Server Error!" });
    }
}

exports.getAvailability = async (req, res) => {
    try {

    } catch(error) {
        console.error(error);
        return res.status(500).json({ e: "Internal Server Error!" });
    }
}

exports.createSchedule = async (req, res) => {
    try {

    } catch(error) {
        console.error(error);
        return res.status(500).json({ e: "Internal Server Error!" });
    }
}

exports.getSchedule = async (req, res) => {
    try {

    } catch(error) {
        console.error(error);
        return res.status(500).json({ e: "Internal Server Error!" });
    }
}

exports.addMember = async (req, res) => {
    try {

    } catch(error) {
        console.error(error);
        return res.status(500).json({ e: "Internal Server Error!" });
    }
}

exports.removeMember = async (req, res) => {
    try {

    } catch(error) {
        console.error(error);
        return res.status(500).json({ e: "Internal Server Error!" });
    }
}